from keep_alive import keep_alive
import discord
import os
import random

keep_alive()

intents = discord.Intents.default()
intents.typing = True
intents.messages = False  # Set messages to False if you don't need message events

# Retrieve the bot token from environment variables
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
  
# Custom messages for specific keywords
custom_messages = {
    "chdhshshjdeip": [
        """**<a:Snow:1170563817072246804><a:snow:1170564089303539884><a:frozen:1168938237738352650>FʀᴏᴢᴇɴMC<a:frozen:1168938237738352650><a:snow:1170564089303539884><a:Snow_snowed:1170564324515926116>
<a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884> ❄️❄️❄️<a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884>
ɪᴘ
Fᴏʀ Jᴀᴠᴀ 
: FrozenMC.minecraftr.us:meow
<a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884> ❄️❄️❄️<a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884>
ɪᴘ ᴀɴᴅ ᴘᴏʀᴛ 
Fᴏʀ ᴍᴄᴘᴇ/ᴍɪɴᴇᴄʀᴀғᴛ ʙᴇᴅʀᴏᴄᴋ                     
ɪᴘ: FrozenMC.minecraftr.us
ᴘᴏʀᴛ: 44962

<a:frozen:1168938237738352650><a:frozen:1168938237738352650><a:snowflake:1170563713208688712><a:snowflake:1170563713208688712><a:snowflake:1170563713208688712><a:frozen:1168938237738352650><a:snowflake:1170563713208688712> <a:snowflake:1170563713208688712><a:snowflake:1170563713208688712><a:frozen:1168938237738352650><a:frozen:1168938237738352650>


**
<a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884><a:snowflake:1170563713208688712><a:snowflake:1170563713208688712><a:snowflake:1170563713208688712><a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884><a:snow:1170564089303539884>:
**Tᴏ Oɴ FʀᴏᴢᴇɴMC Pɪɴɢ Mᴇ Aɴᴅ Sᴀʏ Sᴛᴀʀᴛ**""",
    ],
    "hi": [
        "hello domsto",
        "kaise hoooo",
        "boom boom saste nashheee",
        "maine pi nahi hai pila di gayi hai",
      "Hi I am Chitti the Robot. Speed 1 terahertz, memory 1 zigabyte.",
      "picture abhi baaki hai mele dost",
      "Ek chutki sindoor ki keemat tum kya jaano Ramesh babu",
 
       ],
  
      "a": [ "yo yo yo honisinger",
      "Hi, I'm Chitti the Robot. Speed 1 terahertz, memory 1 zigabyte.","mere pass maa hai",
"kitne aadmi the","demotion pakka hoga tera be","zhuk ke rehna padega Mele Saamne Be","https://tenor.com/oCpFTpQCpgP.gif","https://tenor.com/blWWM.gif","https://tenor.com/en-GB/view/pokemon-pikachu-tongue-stretched-wide-gif-9048715746502460494",
"raj, naam toh suna hoga",
"aaj ek hasi aur baant lo, aaj ek dua aur maang lo, aaj ek ansoo aur pee lo, aaj ek zindagi aur jee lo, aaj ek sapna aur dekh lo, aaj... kya pata, kal ho na ho",
"Don't underestimate the power of a common man",
"Kuch toh log kahenge, logon ka kaam hai kehna",
"Jaa Simran, jee le apni zindagi",
"Aaj mere paas gaadi hai, bungla hai, paisa hai... tumhare paas kya hai",
"Yeh tumhara realism hai, ismein na hero hai, na villain hai, na romance hai, na action hai",
"Swarglok se aaye hain, hum... khatron ke khiladi",
"Yeh haath mujhe de de Thakur",
"Hum tum ek kamre mein bandh ho, aur chaabi kho jaye",
"Mogambo khush hua",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo",
"Rishte mein toh hum tumhare baap lagte hain, naam hai Shahenshah",
"Aap purush hi nahi, mahapurush hain",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bus rukna nahi chahta",
"Babumoshai, zindagi badi honi chahiye, lambi nahi",
"Tareekh pe tareekh, tareekh pe tareekh, tareekh pe tareekh milti rahi hai, lekin insaaf nahi mila my lord, mili hai toh sirf yeh khamoshi",
"Ismein koi doubt nahi, doubtful hai!",
"Rahul, naam toh suna hoga?",
"Picture abhi baaki hai, mere dost",
"Bade miyan to bade miyan, chhote miyan subhanallah",
"Aaj ek, kal do; do din baad chaar",
"Jinke ghar sheeshe ke hote hain, woh doosron par patthar nahi phenka karte",
"Jhakkaas!",
"Bhagwan ke bharose na baithiye, kya pata bhagwan hamare bharose baitha ho",
"Haste haste kat jaaye raste",
"Bachpan mein bachpana tha, ab jawaani mein jawani hai",
"Ghar mein toh kutte bhi sher hote hain",
"Bhagwan ke liye mujhe chhod do",
"Yeh kya kar diya tumne, yeh koi ghar hai, ghanti laga di tumne",
"Koi shak?",
"Don ka intezaar toh gyarah mulkon ki police kar rahi hai, lekin ek baat samajh lo, don ko pakadna mushkil hi nahin, namumkin hai",
"Mauka mile toh panga mat lena",
"Babuji ne kaha gaon chhodo, sab ne kaha paro ko chhodo, paro ne kaha sharab chhodo, lekin tumne kaha... saala, kuch chhodo, chhodo",
"Chulbul Pandey ki kahani mein twist hai",
"Aapke paas Bang Bang hai, aur humare paas... namak hai",
"Raj, naam toh suna hoga",
"Ek baar jo maine commitment kar di, phir main apne aap ki bhi nahi sunta",
"Yeh kya kar diya tune, bada mushkil hai lafzon mein bayan karna",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hain",
"Aap humse humari zindagi maang lete, hum aapko khushi khushi de dete",
"Jab yeh dhai kilo ka haath kisi pe padta hai na, toh aadmi uthta nahi... utth jata hai",
"Tumhara naam kya hai Basanti?",
"Aaj ek, kal doi; do din baad chaar",
"Kaun kambakht bardasht karne ko peeta hai, hum toh peete hai ki yahan par baith sake, tumhe dekhein",
"Badi badi deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo",
"Zindagi badi honi chahiye, lambi nahi Babuji.",
"Kabhi kabhi lagta hai apun hi bhagwan hai.",
"Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
"Mogambo khush hua!",
"Tumse na ho payega!",
"Yeh toh sirf trailer tha, picture abhi baki hai mere dost!",
"Life mein teen cheez kabhi underestimate nahi karna - I, Me, and Myself.",
            "Jhakas!", "Ek baar jo maine commitment kar di, phir main apne aap ki bhi nahi sunta.", "Bhagwan ka diya sab kuch hai, bas dharam ka kya karein?",
            "Ek ladki ko dekha toh aisa laga.", "Kabhi kabhi lagta hai apun hi bhagwan hai.", "Tareekh pe tareekh, tareekh pe tareekh, tareekh pe tareekh milti rahi hai, lekin insaaf nahi mila my lord, mili hai toh sirf yeh tareekh.", "Basanti, inn kutton ke samne mat nachna.", "Haan, main peeta hoon, par tumse darta hoon.", "Tumse na ho payega!", "Babumoshai, zindagi badi honi chahiye, lambi nahi.", "Chakke chhuda de, hum ek kaam karenge.", "Aa bail mujhe maar!", "Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.", "Yeh kya ho raha hai?", "Main tumhe bhool jaon yeh ho nahi sakta.", "Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.", "Ae bhai, all is well!", "Tumse na ho payega!",
            "Bhagwan ke liye mujhe chhod do!",
            "Haste haste kat jayein raste.",
            "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
            "Dosti ka ek usool hai madam, no sorry, no thank you.", "Jab tak tere pair chalenge tab tak tera mood machaenge.", 
            "Tension nahi leneka, sirf dene ka!",
            "Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.", "Mere paas Maa hai.",
            "Babumoshai, zindagi badi honi chahiye, lambi nahi.", "Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
            "Koi doubt mat rakhna, main hamesha yahaan hoon.""Chalo dosto, shuru karte hai!", "Yeh kaafi interesting hai, na?", "Kuch naya seekhte hai, hamesha aage badhte hai.",
            "Main hairaan hoon, yeh kaise ho gaya?", "Sabko swagat hai, kaise ho aap sab?",
            "Bot zindabad!", "Aapka samay shuru hota hai, aur khatam bhi!", 
            "Badi badi deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
            "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
            "Iska toh ek hi formula hai – 'Family first, always!'", 
            "Life mein kuch bhi ho sakta hai, aur yehi exciting part hai.",
            "Dil toh pagal hai, pagal hai!",
            "Tumse na ho payega!", "Jab koi kisi ko saccha pyaar karta hai, toh woh kabhi bhi haar nahi maanta.",
            "Tumhare paas kya hai, mere paas maa hai!",
            "Zindagi lambi nahi, badi honi chahiye, lambi nahi.", "Yeh kya ho raha hai?", "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
            "Tumse na ho payega!", "Bhagwan ke liye mujhe chhod do!", "Haste haste kat jayein raste.", "Chakke chhuda de, hum ek kaam karenge.",
            "Aa bail mujhe maar!", "Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
            "Main tumhe bhool jaon yeh ho nahi sakta.", "Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Chalo dosto, shuru karte hai!",
"Yeh kaafi interesting hai, na?",
"Kuch naya seekhte hai, hamesha aage badhte hai.",
"Main hairaan hoon, yeh kaise ho gaya?",
"Sabko swagat hai, kaise ho aap sab?",
"Bot zindabad!",
"Aapka samay shuru hota hai, aur khatam bhi!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Haste haste kat jayein raste.",
"Bhagwan ke liye mujhe chhod do!",
"Koi doubt mat rakhna, main hamesha yahaan hoon.",
"Ae bhai, all is well!",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Tension nahi leneka, sirf dene ka!",
"Dil garden-garden ho gaya hai.",
"Jab se dekha hai maine tujhko, mujhko kuch kuch hota hai.",
"Bachpan se hi na, mujhe senior bachon ka bohot shauk tha.",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"main tera khoon pee jaoonga!",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Babumoshai, zindagi badi honi chahiye, lambi nahi.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Babumoshai, zindagi badi honi chahiye, lambi nahi.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Koi doubt mat rakhna, main hamesha yahaan hoon.",
"Zindagi mein teen cheezon ke peechey kabhi nahi bhagna chahiye – bus, train aur chakkar.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Tumse na ho payega!",
"Iska toh ek hi formula hai – 'Family first, always!'",
"Bhagwan ke liye mujhe chhod do!",
"Yeh kya ho raha hai?",
"Haste haste kat jayein raste.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Kyun so rahe ho? Agar zindagi mein kuch karna hai toh so jao!",
            "Yeh koi saaman chhota nahi hai, dil se dekho, bahut bada hai.",
            "Jab tak tu apne dil se saath hai, tab tak tere paas kuch kam nahi hai.",
            "Aaj ka din, aaj ki raat, bas yahi waqt hai, kal se sab kuch badal sakta hai.",
            "Life mein jitna bhi try karo, kuch na kuch toh chhootega hi. Toh jahanpanah, shuru ho jaaye?", 
            "Yeh zindagi na milegi dobara, isiliye thoda chill karo.",
            "Aaj ek naya chapter shuru hota hai, dekhte hai kya likha gaya hai.",
            "Kabhi kabhi lagta hai apun hi bhagwan hai, woh bhi road pe.", 
            "Is duniya mein do tarah ke log hote hai, winners aur losers. Magar zindagi har loser ko ek mauka deti hai, jeetne ka.",
            "Har kadam par koi raaste ka theka nahi hota, bas chalna padta hai.",
            "Jab life mein utar-chadhav aaye, toh bas smile karo, kyunki duniya gol hai.",
            "Aaj ka din bada important hai, kyunki aaj ka hi toh kal ka bridge banta hai.", "Apne sapno ko sach banane ke liye, pehle unhe dekho, fir unhe pura karo.", 
            "Har mushkil ka hal hai patience aur ek cup chai ka.",
            "Life ka asli mazaa toh tab aata hai jab saath mein friends ho, aur kuch masti ho.", "Zindagi mein kuch bhi ho, ek acchi movie ka asar hamesha hota hai.",
            "Har kahani ka ek twist hota hai, aur woh twist tab aata hai jab tu khud apni kahani likh raha hota hai.",
            "Zindagi mein har din ek naya lesson sikha deti hai, bas dhyan se suno aur samjho.", "Aaj ka din sirf ek din nahi hai, yeh ek naya chapter hai tumhare jeevan ka.",
            "Kabhi kabhi lagta hai humare decisions hi humare destiny ko define karte hai.", 
            "Aaj ka din, aaj ki raat, bas yahi waqt hai, kal se sab kuch badal sakta hai.", 
            "Har sapna ek kahani hai, aur har kahani mein ek hero chupa hota hai, woh hero tum ho.", "Apne dil ki suno, kyunki wohi tumhe sahi raaste par leke jaayega.", 
            "Zindagi mein kuch bhi ho, ek acchi movie ka asar hamesha hota hai.",
            "Har kahani ka ek twist hota hai, aur woh twist tab aata hai jab tu khud apni kahani likh raha hota hai.", 
            "Zindagi mein har din ek naya lesson sikha deti hai, bas dhyan se suno aur samjho.", 
            "Aaj ka din sirf ek din nahi hai, yeh ek naya chapter hai tumhare jeevan ka.", 
            "Kabhi kabhi lagta hai humare decisions hi humare destiny ko define karte hai.", "Aaj ka din, aaj ki raat, bas yahi waqt hai, kal se sab kuch badal sakta hai.",
            "Har sapna ek kahani hai, aur har kahani mein ek hero chupa hota hai, woh hero tum ho.", "Apne dil ki suno, kyunki wohi tumhe sahi raaste par leke jaayega.",
"Jab tak teri coffee garam hai, tab tak tera mood bhi hota hai, remember it.",
"Life mein options hamesha do hote hain, ek toh ho jaaye, dusra... 'Hum kisi se kam nahi!', remember it.",
"Agar zindagi mein thoda drama nahi hota, toh kahani boring ho jaati, remember it.",
"Yeh zindagi ek jigsaw puzzle ki tarah hai, kabhi easy, kabhi missing pieces, remember it.",
"Is duniya mein do tarah ke log hote hain, ek jo pizza khate hain, aur dusre log jinhone abhi tak try nahi kiya, remember it.",
"Har kahani mein twist zaroori hota hai, warna kahani flat ho jaati hai, aur flat toh sirf pizza hota hai, remember it.",
"Kabhi-kabhi lagta hai, apun hi apni favorite character hai is duniya ke script mein, remember it.",
"Life mein ek hi rule hai, no rules! Bas masti karo bhai, remember it.",
"Agar life mein kuch tough ho raha hai, toh samajh jao, scene on hai!, remember it.",
"Har exam ka solution ek hi hota hai, 'Kuch bhi likh do, jo aaya dimaag mein.', remember it.",
"Zindagi mein kuch bhi ho, ek acchi comedy movie ka asar hamesha hota hai, remember it.",
"Jab life mein kuch bura ho jaaye, toh yaad rakhna – 'Kal se sab kuch normal ho jaayega, maybe.', remember it.",
"Har kahani mein ek villain zaroori hota hai, warna hero ka kya kaam?, remember it.",
"Kabhi-kabhi lagta hai, humare pet mein butterflies nahi, dinosaurs chal rahe hote hain., remember it.",
"Aaj ka din sirf ek din nahi hai, yeh ek episode hai teri life ka, toh bindaas dekh!, remember it.",
"Jab tak tera sense of humor alive hai, tab tak teri heartbeat bhi strong hai., remember it.",
"Zindagi mein kuch bhi ho, ek acchi joke ka asar hamesha hota hai, try maar!, remember it.",
"Life mein kabhi kabhi lagta hai, jaise hum ek giant reality show mein hain, aur humara script writer Zarur., remember it.",
"Kabhi-kabhi lagta hai, zindagi ek infinite scroll hai, bas keep scrolling, kuch na kuch toh mil hi jaayega., remember it.",
"Life mein badi badi chhoti chhoti baatein hoti rehti hain, par tension lene ka nahi, kyunki 'All is well!'., remember it.",
"Jab tak tera Netflix subscription active hai, tab tak tera entertainment quotient high rahega., remember it.",
"Life mein jo bhi ho, ek acchi meme ka asar hamesha hota hai, bas hashtag funnylife!, remember it.",
"Kabhi-kabhi lagta hai, hum log hi universe ki favorite sitcom characters hain., remember it.",
"Zindagi mein kuch bhi ho, ek accha punchline sabko pasand aata hai, try maar!, remember it.",
"Jab tak teri playlist cool hai, tab tak tera swag bhi cool rahega., remember it.",
"Life mein kabhi-kabhi lagta hai, jaise hum ek giant puzzle ke pieces hain, bas apna piece dhundo!, remember it.",
           ],
  "e": [

"Kya tumhe yakeen hai?", 
"Mere paas maa hai.","mere pass maa hai",
"kitne aadmi the",
"raj, naam toh suna hoga",
"aaj ek hasi aur baant lo, aaj ek dua aur maang lo, aaj ek ansoo aur pee lo, aaj ek zindagi aur jee lo, aaj ek sapna aur dekh lo, aaj... kya pata, kal ho na ho",
"Don't underestimate the power of a common man",
"Kuch toh log kahenge, logon ka kaam hai kehna",
"Jaa Simran, jee le apni zindagi",
"Aaj mere paas gaadi hai, bungla hai, paisa hai... tumhare paas kya hai",
"Yeh tumhara realism hai, ismein na hero hai, na villain hai, na romance hai, na action hai",
"Swarglok se aaye hain, hum... khatron ke khiladi",
"Yeh haath mujhe de de Thakur",
"Hum tum ek kamre mein bandh ho, aur chaabi kho jaye",
"Mogambo khush hua",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo",
"Rishte mein toh hum tumhare baap lagte hain, naam hai Shahenshah",
"Aap purush hi nahi, mahapurush hain",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bus rukna nahi chahta",
"Babumoshai, zindagi badi honi chahiye, lambi nahi",
"Tareekh pe tareekh, tareekh pe tareekh, tareekh pe tareekh milti rahi hai, lekin insaaf nahi mila my lord, mili hai toh sirf yeh khamoshi",
"Ismein koi doubt nahi, doubtful hai!",
"Rahul, naam toh suna hoga?",
"Picture abhi baaki hai, mere dost",
"Bade miyan to bade miyan, chhote miyan subhanallah",
"Aaj ek, kal do; do din baad chaar",
"Jinke ghar sheeshe ke hote hain, woh doosron par patthar nahi phenka karte",
"Jhakkaas!",
"Bhagwan ke bharose na baithiye, kya pata bhagwan hamare bharose baitha ho",
"Haste haste kat jaaye raste",
"Bachpan mein bachpana tha, ab jawaani mein jawani hai",
"Ghar mein toh kutte bhi sher hote hain",
"Bhagwan ke liye mujhe chhod do",
"Yeh kya kar diya tumne, yeh koi ghar hai, ghanti laga di tumne",
"Koi shak?",
"Don ka intezaar toh gyarah mulkon ki police kar rahi hai, lekin ek baat samajh lo, don ko pakadna mushkil hi nahin, namumkin hai",
"Mauka mile toh panga mat lena",
"Babuji ne kaha gaon chhodo, sab ne kaha paro ko chhodo, paro ne kaha sharab chhodo, lekin tumne kaha... saala, kuch chhodo, chhodo",
"Chulbul Pandey ki kahani mein twist hai",
"Aapke paas Bang Bang hai, aur humare paas... namak hai",
"Raj, naam toh suna hoga",
"Ek baar jo maine commitment kar di, phir main apne aap ki bhi nahi sunta",
"Yeh kya kar diya tune, bada mushkil hai lafzon mein bayan karna",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hain",
"Aap humse humari zindagi maang lete, hum aapko khushi khushi de dete",
"Jab yeh dhai kilo ka haath kisi pe padta hai na, toh aadmi uthta nahi... utth jata hai",
"Tumhara naam kya hai Basanti?",
"Aaj ek, kal doi; do din baad chaar",
"Kaun kambakht bardasht karne ko peeta hai, hum toh peete hai ki yahan par baith sake, tumhe dekhein",
"Badi badi deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo",
"Zindagi badi honi chahiye, lambi nahi Babuji.",
"Kabhi kabhi lagta hai apun hi bhagwan hai.",
"Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
"Mogambo khush hua!",
"Tumse na ho payega!",
"Yeh toh sirf trailer tha, picture abhi baki hai mere dost!",
"Life mein teen cheez kabhi underestimate nahi karna - I, Me, and Myself.",
            "Jhakas!", "Ek baar jo maine commitment kar di, phir main apne aap ki bhi nahi sunta.", "Bhagwan ka diya sab kuch hai, bas dharam ka kya karein?",
            "Ek ladki ko dekha toh aisa laga.",
    "Kabhi kabhi lagta hai apun hi bhagwan hai.",
    "Tareekh pe tareekh, tareekh pe tareekh, tareekh pe tareekh milti rahi hai, lekin insaaf nahi mila my lord, mili hai toh sirf yeh tareekh.",
    "Basanti, inn kutton ke samne mat nachna.",
    "Haan, main peeta hoon, par tumse darta hoon.", "Tumse na ho payega!",
    "Babumoshai, zindagi badi honi chahiye, lambi nahi.",
    "Chakke chhuda de, hum ek kaam karenge.",
    "Aa bail mujhe maar!",
    "Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.", 
    "Yeh kya ho raha hai?", "Main tumhe bhool jaon yeh ho nahi sakta.", 
    "Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
    "Ae bhai, all is well!", "Tumse na ho payega!",
            "Bhagwan ke liye mujhe chhod do!", 
    "Haste haste kat jayein raste.",
    "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
    "Dosti ka ek usool hai madam, no sorry, no thank you.", "Jab tak tere pair chalenge tab tak tera mood machaenge.", 
    "Tension nahi leneka, sirf dene ka!", 
    "Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
    "Mere paas Maa hai.", "Babumoshai, zindagi badi honi chahiye, lambi nahi.",
    "Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
    "Koi doubt mat rakhna, main hamesha yahaan hoon.""Chalo dosto, shuru karte hai!",
    "Yeh kaafi interesting hai, na?", "Kuch naya seekhte hai, hamesha aage badhte hai.",
    "Main hairaan hoon, yeh kaise ho gaya?", "Sabko swagat hai, kaise ho aap sab?",
    "Bot zindabad!",
    "Aapka samay shuru hota hai, aur khatam bhi!",
    "Badi badi deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
    "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.", "Iska toh ek hi formula hai – 'Family first, always!'",
    "Life mein kuch bhi ho sakta hai, aur yehi exciting part hai.", "Dil toh pagal hai, pagal hai!",
    "Tumse na ho payega!", "Jab koi kisi ko saccha pyaar karta hai, toh woh kabhi bhi haar nahi maanta.",
    "Tumhare paas kya hai, mere paas maa hai!",
    "Zindagi lambi nahi, badi honi chahiye, lambi nahi.", "Yeh kya ho raha hai?",
    "Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
    "Tumse na ho payega!", "Bhagwan ke liye mujhe chhod do!", "Haste haste kat jayein raste.", "Chakke chhuda de, hum ek kaam karenge.",
    "Aa bail mujhe maar!", "Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
    "Main tumhe bhool jaon yeh ho nahi sakta.",
    "Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Chalo dosto, shuru karte hai!",
"Yeh kaafi interesting hai, na?",
"Kuch naya seekhte hai, hamesha aage badhte hai.",
"Main hairaan hoon, yeh kaise ho gaya?",
"Sabko swagat hai, kaise ho aap sab?",
"Bot zindabad!",
"Aapka samay shuru hota hai, aur khatam bhi!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Haste haste kat jayein raste.",
"Bhagwan ke liye mujhe chhod do!",
"Koi doubt mat rakhna, main hamesha yahaan hoon.",
"Ae bhai, all is well!",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Tension nahi leneka, sirf dene ka!",
"Dil garden-garden ho gaya hai.",
"Jab se dekha hai maine tujhko, mujhko kuch kuch hota hai.",
"Bachpan se hi na, mujhe senior bachon ka bohot shauk tha.",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"main tera khoon pee jaoonga!",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Babumoshai, zindagi badi honi chahiye, lambi nahi.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Babumoshai, zindagi badi honi chahiye, lambi nahi.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Koi doubt mat rakhna, main hamesha yahaan hoon.",
"Zindagi mein teen cheezon ke peechey kabhi nahi bhagna chahiye – bus, train aur chakkar.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Tumse na ho payega!",
"Iska toh ek hi formula hai – 'Family first, always!'",
"Bhagwan ke liye mujhe chhod do!",
"Yeh kya ho raha hai?",
"Haste haste kat jayein raste.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Chakke chhuda de, hum ek kaam karenge.",
"Aa bail mujhe maar!",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Yeh kya ho raha hai?",
"Main tumhe bhool jaon yeh ho nahi sakta.",
"Chhote, chhote bhaiyon ke bade bhaiya, aaj tumhe sab kuch pata chal jayega.",
"Ae bhai, all is well!",
"Tumse na ho payega!",
"Bhagwan ke liye mujhe chhod do!",
"Haste haste kat jayein raste.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Dosti ka ek usool hai madam, no sorry, no thank you.",
"Jab tak tere pair chalenge tab tak tera mood machaenge.",
"Tension nahi leneka, sirf dene ka!",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon... bas rukna nahi chahta.",
"Mere paas Maa hai.",
"Kuch kuch hota hai, Rahul, tum nahi samjhoge.",
"Yeh kya ho raha hai?",
"Rahul, naam toh suna hoga.",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo.",
"Rahul, naam toh suna hoga.",
"Tumse na ho payega!",
"Rab diyaan rakhyaan!",
"Kyun so rahe ho? Agar zindagi mein kuch karna hai toh so jao!", "Yeh koi saaman chhota nahi hai, dil se dekho, bahut bada hai.", "Jab tak tu apne dil se saath hai, tab tak tere paas kuch kam nahi hai.", "Aaj ka din, aaj ki raat, bas yahi waqt hai, kal se sab kuch badal sakta hai.", "Life mein jitna bhi try karo, kuch na kuch toh chhootega hi. Toh jahanpanah, shuru ho jaaye?", "Yeh zindagi na milegi dobara, isiliye thoda chill karo.", "Aaj ek naya chapter shuru hota hai, dekhte hai kya likha gaya hai.", "Kabhi kabhi lagta hai apun hi bhagwan hai, woh bhi road pe.", "Is duniya mein do tarah ke log hote hai, winners aur losers. Magar zindagi har loser ko ek mauka deti hai, jeetne ka.", "Har kadam par koi raaste ka theka nahi hota, bas chalna padta hai.", "Jab life mein utar-chadhav aaye, toh bas smile karo, kyunki duniya gol hai.", "Aaj ka din bada important hai, kyunki aaj ka hi toh kal ka bridge banta hai.", "Apne sapno ko sach banane ke liye, pehle unhe dekho, fir unhe pura karo.", "Har mushkil ka hal hai patience aur ek cup chai ka.", "Life ka asli mazaa toh tab aata hai jab saath mein friends ho, aur kuch masti ho.", "Zindagi mein kuch bhi ho, ek acchi movie ka asar hamesha hota hai.", "Har kahani ka ek twist hota hai, aur woh twist tab aata hai jab tu khud apni kahani likh raha hota hai.",
            "Zindagi mein har din ek naya lesson sikha deti hai, bas dhyan se suno aur samjho.", "Aaj ka din sirf ek din nahi hai, yeh ek naya chapter hai tumhare jeevan ka.",
            "Kabhi kabhi lagta hai humare decisions hi humare destiny ko define karte hai.", 
            "Aaj ka din, aaj ki raat, bas yahi waqt hai, kal se sab kuch badal sakta hai.", "Har sapna ek kahani hai, aur har kahani mein ek hero chupa hota hai, woh hero tum ho.", "Apne dil ki suno, kyunki wohi tumhe sahi raaste par leke jaayega.", "Zindagi mein kuch bhi ho, ek acchi movie ka asar hamesha hota hai.", "Har kahani ka ek twist hota hai, aur woh twist tab aata hai jab tu khud apni kahani likh raha hota hai.", "Zindagi mein har din ek naya lesson sikha deti hai, bas dhyan se suno aur samjho.", "Aaj ka din sirf ek din nahi hai, yeh ek naya chapter hai tumhare jeevan ka.", "Kabhi kabhi lagta hai humare decisions hi humare destiny ko define karte hai.", "Aaj ka din, aaj ki raat, bas yahi waqt hai, kal se sab kuch badal sakta hai.", "Har sapna ek kahani hai, aur har kahani mein ek hero chupa hota hai, woh hero tum ho.", "Apne dil ki suno, kyunki wohi tumhe sahi raaste par leke jaayega.",
"Jab tak teri coffee garam hai, tab tak tera mood bhi hota hai, remember it.",
"Life mein options hamesha do hote hain, ek toh ho jaaye, dusra... 'Hum kisi se kam nahi!', remember it.",
"Agar zindagi mein thoda drama nahi hota, toh kahani boring ho jaati, remember it.",
"Yeh zindagi ek jigsaw puzzle ki tarah hai, kabhi easy, kabhi missing pieces, remember it.",
"Is duniya mein do tarah ke log hote hain, ek jo pizza khate hain, aur dusre log jinhone abhi tak try nahi kiya, remember it.",
"Har kahani mein twist zaroori hota hai, warna kahani flat ho jaati hai, aur flat toh sirf pizza hota hai, remember it.",
"Kabhi-kabhi lagta hai, apun hi apni favorite character hai is duniya ke script mein, remember it.",
"Life mein ek hi rule hai, no rules! Bas masti karo bhai, remember it.",
"Agar life mein kuch tough ho raha hai, toh samajh jao, scene on hai!, remember it.",
"Har exam ka solution ek hi hota hai, 'Kuch bhi likh do, jo aaya dimaag mein.', remember it.",
"Zindagi mein kuch bhi ho, ek acchi comedy movie ka asar hamesha hota hai, remember it.",
"Jab life mein kuch bura ho jaaye, toh yaad rakhna – 'Kal se sab kuch normal ho jaayega, maybe.', remember it.",
"Har kahani mein ek villain zaroori hota hai, warna hero ka kya kaam?, remember it.",
"Kabhi-kabhi lagta hai, humare pet mein butterflies nahi, dinosaurs chal rahe hote hain., remember it.",
"Aaj ka din sirf ek din nahi hai, yeh ek episode hai teri life ka, toh bindaas dekh!, remember it.",
"Jab tak tera sense of humor alive hai, tab tak teri heartbeat bhi strong hai., remember it.",
"Zindagi mein kuch bhi ho, ek acchi joke ka asar hamesha hota hai, try maar!, remember it.",
"Life mein kabhi kabhi lagta hai, jaise hum ek giant reality show mein hain, aur humara script writer Zarur., remember it.",
"Kabhi-kabhi lagta hai, zindagi ek infinite scroll hai, bas keep scrolling, kuch na kuch toh mil hi jaayega., remember it.",
"Life mein badi badi chhoti chhoti baatein hoti rehti hain, par tension lene ka nahi, kyunki 'All is well!'., remember it.",
"Jab tak tera Netflix subscription active hai, tab tak tera entertainment quotient high rahega., remember it.",
"Life mein jo bhi ho, ek acchi meme ka asar hamesha hota hai, bas hashtag funnylife!, remember it.",
"Kabhi-kabhi lagta hai, hum log hi universe ki favorite sitcom characters hain., remember it.",
"Zindagi mein kuch bhi ho, ek accha punchline sabko pasand aata hai, try maar!, remember it.",
"Jab tak teri playlist cool hai, tab tak tera swag bhi cool rahega., remember it.",
"Life mein kabhi-kabhi lagta hai, jaise hum ek giant puzzle ke pieces hain, bas apna piece dhundo!, remember it.",
"main tera khoon pee jaoonga!",
"Rahul, naam toh suna hoga.",
"Babuji ne kaha gaon chhod do, sab ne kaha Paro ko chhod do.",
"Jaa Simran jaa, jee le apni zindagi.",
"Yeh haath mujhe de de, Thakur!",
"Kaun kambakht bardasht karne ko peeta hai?",
"Koi mujhe junglee kahe, toh main kehta hoon junglee kahe ko.",
"Ek chutki sindoor ki keemat tum kya jaano Ramesh babu.",
"Tumse na ho paayega.",
"Yeh kya ho raha hai?",
"Jhakaas!",
"Picture abhi baaki hai, mere dost.",
"Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
"Mogambo khush hua.",
"Kitne aadmi the?",
"Don ko pakadna mushkil hi nahin, namumkin hai.",
"Aaj mere paas bangla hai, gaadi hai, bank balance hai, kya hai tumhare paas?",
"Rishte mein toh hum tumhare baap lagte hai, naam hai Shahenshah.",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon ... bus rukna nahi chahta.",
"Yeh tumhare baap ka ghar nahin, police station hai. Aur is mein thane adhikari mera naukar hai.",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Swagat nahi karoge aap hamara?",
"Jab kisi ko kuch nahi milta na ... toh woh deta kyun hai?",
"Mai jhooth nahi bolta!",
"Tum ek machhar ke samne stand nahin kar sakte.",
"Mein udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon ... bus rukna nahi chahta.",
"Mere dost, zindagi lambi nahi, badi honi chahiye.",
"Rahul, naam toh suna hoga.",
"Basanti, inn kutton ke samne mat nachna.",
"Tumhara naam kya hai, Basanti?",
"Kya tumhe yakeen hai?",
"Rishte mein toh hum tumhare baap lagte hai, naam hai Shahenshah.",
"Yeh kya ho raha hai?",
"Mujhe jungli billiyan bohot pasand hai.",
"Arey o Sambha, kitna inaam rakhe hai sarkar hum par?",
"Bhagwan ke bharose na baithiye, kya pata bhagwan hamare bharose baitha ho.",
"Saara sheher mujhe Loin ke naam se jaanta hai.",
"Mai aaj bhi pheke hue paise nahin uthata.",
"Prem naam hai mera, Prem Chopra.",
"kameene, main tera khoon pee jaoonga!",
"Aaj ek hasi aur baant lo, aaj ek dua aur maang lo, aaj ek ansoo aur pee lo, aaj ek zindagi aur jee lo, aaj ek sapna aur dekh lo, aaj... kya pata, kal ho na ho!",
"Yeh dil maange more.",
"Kuch kuch hota hai, Rahul. Tum nahin samjhoge.",
"Chak De Phatte!",
"Khabardar jo kisi ne usse touch kiya.",
"Kaun kambakht bardasht karne ko peeta hai?",
"Pushpa, I hate tears.",
"Rahul, naam toh suna hoga.",
"Picture abhi baaki hai, mere dost.",
"Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
"Yeh haath mujhe de de, Thakur!",
"Kaun kambakht bardasht karne ko peeta hai?",
"Koi mujhe junglee kahe, toh main kehta hoon junglee kahe ko.",
"Ek chutki sindoor ki keemat tum kya jaano Ramesh babu.",
"Tumse na ho paayega.",
"Yeh kya ho raha hai?",
"Jhakaas!",
"Picture abhi baaki hai, mere dost.",
"Bade bade deshon mein aisi chhoti chhoti baatein hoti rehti hai, Senorita.",
"Mogambo khush hua.",
"Kitne aadmi the?",
"Don ko pakadna mushkil hi nahin, namumkin hai.",
"Aaj mere paas bangla hai, gaadi hai, bank balance hai, kya hai tumhare paas?",
"Rishte mein toh hum tumhare baap lagte hai, naam hai Shahenshah.",
"Main udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon ... bus rukna nahi chahta.",
"Yeh tumhare baap ka ghar nahin, police station hai. Aur is mein thane adhikari mera naukar hai.",
"Kabhi kabhi kuch jeetne ke liye kuch haarna bhi padta hai, aur haar kar jeetne wale ko baazigar kehte hai.",
"Swagat nahi karoge aap hamara?",
"Jab kisi ko kuch nahi milta na ... toh woh deta kyun hai?",
"Mai jhooth nahi bolta!",
"Tum ek machhar ke samne stand nahin kar sakte.",
"Mein udna chahta hoon, daudna chahta hoon, girna bhi chahta hoon ... bus rukna nahi chahta.",
"Mere dost, zindagi lambi nahi, badi honi chahiye.",
"Rahul, naam toh suna hoga.",
  
    
  ],
        "sus": [
            "veryyy sussysysusy miaaa"
        ],
        "t": [
            "talking talking talking i like it :)",        "https://media.tenor.com/9VIXiXV2cAYAAAAM/death-note.gif",
  ],
    "doremon": [
    "Galaxy (MrDoraemon/Owner) Ke Aghe Koi Bol Sakta hai kya!"
    ],
  "dm":[
    "dm me mat jao na khelo na :( ya kuch alag karne ja rahe"
  ],
  "ja": [
    "Meli Jaati Nahi Teri Aati Nahi 😂",
    "Parampara. Pratishtha. Anushasan. Yeh is gurukul ke teen stambh hai.",
    "mogambo khush hua"
  ],
    "khush": [
      "Mogambo Khush Hua"
    ],
  "pass": [
    "Mele Pass Ram Storage CPU gf hai tere pass kya"
  ],
  "is": [
    "All izz Well"
  ],
  "Bye":[
    "Tussi Ja Rahe! Mat Jao:(",
    "Isko Utha Le Baba!"
  ],
  
  "hello": [
        "hello domsto",
        "kaise hoooo",
        "boom boom saste nashheee",
        "maine pi nahi hai pila di gayi hai",
      "Hi, I'm Chitti the Robot. Speed 1 terahertz, memory 1 zigabyte."
  ],
  "ban": [
    "dede isko ban"
  ],
  "skull": [
    ":skull:"
  ],
  "kya hua": [
    "Phucho Ki Kya Nahi Hua Haye:("
  ],
  "tu faltu": [
    "https://media.tenor.com/9VIXiXV2cAYAAAAM/death-note.gif"
  ],
  "tujhe faltu": [
    "https://media.tenor.com/9VIXiXV2cAYAAAAM/death-note.gif"
  ],
  "aja": [
    "uske karan arjun ayenge Ayenge Dhek lena (mela overacting ka 50 rs na kaat lena :("
  ],
  "yes or no": [
    "No",
    "Yes"
  ],
  "inferno": [
    "mat jao InfernoSMP mat jao",
    "mat jao simran mat jao"
  ],
  "logfddin": [
    """**<a:Snow:1170563817072246804><a:snow:1170564089303539884><a:frozen:1168938237738352650>FʀᴏᴢᴇɴMC<a:frozen:1168938237738352650><a:snow:1170564089303539884><a:Snow_snowed:1170564324515926116>
<a:cf_snowflake6:1170562465378074817> Follow the given instructions to register/login FrozenMC <a:cf_snowflake6:1170562465378074817>
<a:flecha:1166230234190848051> Join The Game If You Are First time joining you will see /register (password)  ingame chats of yours
<a:flecha:1166230234190848051> then type /register (yourpassword) like /register (DoraemonIsCool)
<a:flecha:1166230234190848051> After Register If You Leave 
<a:flecha:1166230234190848051>  You Have To Login 
Type /login (password)
That you used in /register (pass)
<a:flecha:1166230234190848051>For example I used/login DoraemonIsCool
And You Are Logged
<a:flecha:1166230234190848051>To Keep Your Account Safe And Secure We Have Did this have fun!**"""
  ],
  "register": [
    """**<a:Snow:1170563817072246804><a:snow:1170564089303539884><a:frozen:1168938237738352650>FʀᴏᴢᴇɴMC<a:frozen:1168938237738352650><a:snow:1170564089303539884><a:Snow_snowed:1170564324515926116>
<a:cf_snowflake6:1170562465378074817> Follow the given instructions to register/login FrozenMC <a:cf_snowflake6:1170562465378074817>
<a:flecha:1166230234190848051> Join The Game If You Are First time joining you will see /register (password)  ingame chats of yours
<a:flecha:1166230234190848051> then type /register (yourpassword) like /register (DoraemonIsCool)
<a:flecha:1166230234190848051> After Register If You Leave 
<a:flecha:1166230234190848051>  You Have To Login 
Type /login (password)
That you used in /register (pass)
<a:flecha:1166230234190848051>For example I used/login DoraemonIsCool
And You Are Logged
<a:flecha:1166230234190848051>To Keep Your Account Safe And Secure We Have Did this have fun!**"""
  ],
  "startffffehshsj": [
    """"<a:Snow:1170563817072246804><a:snow:1170564089303539884><a:frozen:1168938237738352650>FʀᴏᴢᴇɴMC<a:frozen:1168938237738352650><a:snow:1170564089303539884><a:Snow_snowed:1170564324515926116>
<a:cf_snowflake6:1170562465378074817> ** Follow the given instructions to start the server** <a:cf_snowflake6:1170562465378074817>
<a:flecha:1166230234190848051> Go To This Website https://falixnodes.net/start
<a:flecha:1166230234190848051> Enter This Ip: **rubin-free.falixserver.net:44962**
<a:flecha:1166230234190848051> Enter This Password: **falixnodes
<a:flecha:1166230234190848051> Enter Ip On Website
<a:flecha:1166230234190848051> Verify Captcha
<a:flecha:1166230234190848051>  Submit And Enjoy Playing Our SMP Need Ip,timer ping me and say like (pingme) timer i will provide information/instructions"""
  ],
  "timeffr": [
    """"**<a:Snow:1170563817072246804><a:snow:1170564089303539884><a:frozen:1168938237738352650>FʀᴏᴢᴇɴMC<a:frozen:1168938237738352650><a:snow:1170564089303539884><a:Snow_snowed:1170564324515926116>
<a:cf_snowflake6:1170562465378074817> ** Follow the given instructions to extand the timer<a:cf_snowflake6:1170562465378074817>
<a:flecha:1166230234190848051> Go To This Website ||https://client.falixnodes.net/timer?id=1160662||
<a:flecha:1166230234190848051> Scroll Down 
<a:flecha:1166230234190848051>Verify Captcha
<a:flecha:1166230234190848051> Wait 10-15 Seconds
<a:flecha:1166230234190848051> Click On Submit
<a:flecha:1166230234190848051> Only 1 Hour Added
Max Limit 2 So Keep Increasing The Timer""",
  ]
 
}

@client.event
async def on_ready():
    print(f"Logged in as {client.user.name}")
    await client.change_presence(activity=discord.Game('Swag Hai Apna ð'))

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    content = message.content.lower()

    # Check for keywords in the message content
    for keyword, replies in custom_messages.items():
        if keyword in content:
            reply = random.choice(replies)
            await message.channel.send(reply)
            return

client.run(DISCORD_TOKEN)
